INSERT INTO TBL_SELLER(NAME, SKU_PREFIX) VALUES('cloudtail','ct');
INSERT INTO TBL_SELLER(NAME, SKU_PREFIX) VALUES('saysha','ss');

INSERT INTO TBL_CATEGORY(NAME) VALUES('PANTS');
INSERT INTO TBL_CATEGORY(NAME) VALUES('SOCKS');
INSERT INTO TBL_CATEGORY(NAME) VALUES('SHIRTS');

INSERT INTO TBL_BRAND(NAME) VALUES('PUMA');
INSERT INTO TBL_BRAND(NAME) VALUES('ARROW');

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ct-xyzuw','Puma Dark Socks',200.45,
'BLACK','M','SALE',
2,1,1);

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ct-xyzvw','Puma Dark Socks',210.45,
'RED','L','SALE',
2,1,1);

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ct-xyzew','Puma Dark Socks',200.45,
'RED','XL','SALE',
2,1,1);

----------------------------------

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ct-xyzuww','Arrow Dark Socks',200.45,
'BLACK','M','SALE',
2,2,1);

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ct-xyzvww','Arrow Dark Socks',210.45,
'RED','L','SALE',
2,2,1);

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ct-xyzeww','Arrow Dark Socks',200.45,
'RED','XL','SALE',
2,2,1);

------------------------------------------------------

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ss-xyzuw','Arrow Dark Socks',200.45,
'BLACK','M','SALE',
2,2,1);

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ss-xyzvw','Arrow Dark Socks',210.45,
'RED','L','SALE',
2,2,1);

INSERT INTO TBL_PRODUCT(
SKU, NAME, PRICE,
COLOR_NAME, PRODUCT_SIZE, STATUS,
CATEGORY_ID, BRAND_ID, SELLER_ID)
VALUES('ss-xyzew','Arrow Dark Socks',200.45,
'RED','XL','SALE',
2,2,2);
